### ISSUE TITLE
Rajya Sabha and Lok Sabha Attendance Service

### ISSUE THREAD

**Issue by areai51** [areai51/my-india#3]
Create an ng2 service that hits a Web Service and using RxJS with methods that return an object that can be directly consumed by the `<bar-chart>` component 

Reference API
lok sabha attendence - https://data.gov.in/node/85987/datastore/export/json
Rajya Sabha Attendence- https://data.gov.in/node/982241/datastore/export/json

**Comment by Aakash-Goel** [comment]
A common service (our-leaders.service) is being created for Lok Sabha and Rajya Sabha Attendence. Closing this ticket and opening a new ticket to create a directive for consuming the data.

**Comment by Aakash-Goel** [comment]
Closed this ticket as complete. And opening new ticket for consuming the data using directive.
